tickers:
  - AALI.JK
  - ACES.JK
  - ADRO.JK
  - AKRA.JK
  - ANTM.JK
  - ASII.JK
  - BBCA.JK
  - BBNI.JK
  - BBRI.JK
  - BBTN.JK
  - BMRI.JK
  - BSDE.JK
  - CPIN.JK
  - EXCL.JK
  - GGRM.JK
  - HMSP.JK
  - ICBP.JK
  - INCO.JK
  - INDF.JK
  - INKP.JK
  - INTP.JK
  - ITMG.JK
  - JSMR.JK
  - KLBF.JK
  - MAPI.JK
  - MEDC.JK
  - MNCN.JK
  - PGAS.JK
  - PTBA.JK
  - PTPP.JK
  - PWON.JK
  - SCMA.JK
  - SMGR.JK
  - SMRA.JK
  - TBIG.JK
  - TINS.JK
  - TLKM.JK
  - TOWR.JK
  - UNTR.JK
  - UNVR.JK
  - WIKA.JK
  - WSKT.JK
