[project]
name = "idx-stocks-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4==4.14.3",
    "cvxpy==1.7.5",
    "flask==3.1.2",
    "ipykernel>=7.1.0",
    "matplotlib==3.10.8",
    "numpy==2.4.0",
    "pandas==2.3.3",
    "pytest==9.0.2",
    "requests==2.32.5",
    "scipy==1.16.3",
    "yfinance==1.0",
]
